USE DATABASE IMT577_DW_KASHYAP_JAGWANI;

--PASS THROUGH VIEWS
CREATE OR REPLACE SECURE VIEW VW_DIM_CHANNEL AS
(
SELECT DIMCHANNELID, CHANNELID, CHANNELCATEGORYID, CHANNELNAME, CHANNELCATEGORY
FROM DIM_CHANNEL
);

CREATE OR REPLACE SECURE VIEW VW_DIM_CUSTOMER AS
(
SELECT DIMCUSTOMERID, DIMLOCATIONID, CUSTOMERID, CUSTOMERFULLNAME, CUSTOMERFIRSTNAME, CUSTOMERLASTNAME, CUSTOMERGENDER
FROM DIM_CUSTOMER
);

CREATE OR REPLACE SECURE VIEW VW_DIM_DATE AS
(
SELECT DATE_PKEY, 
  DATE date, 
  FULL_DATE_DESC, 
  DAY_NUM_IN_WEEK, 
  DAY_NUM_IN_MONTH, 
  DAY_NUM_IN_YEAR, 
  DAY_NAME, 
  DAY_ABBREV, 
  WEEKDAY_IND, 
  US_HOLIDAY_IND, 
  _HOLIDAY_IND, 
  MONTH_END_IND, 
  WEEK_BEGIN_DATE_NKEY, 
  WEEK_BEGIN_DATE, 
  WEEK_END_DATE_NKEY, 
  WEEK_END_DATE, 
  WEEK_NUM_IN_YEAR, 
  MONTH_NAME, 
  MONTH_ABBREV, 
  MONTH_NUM_IN_YEAR, 
  YEARMONTH, 
  QUARTER, 
  YEARQUARTER, 
  YEAR, 
  FISCAL_WEEK_NUM, 
  FISCAL_MONTH_NUM, 
  FISCAL_YEARMONTH, 
  FISCAL_QUARTER, 
  FISCAL_YEARQUARTER, 
  FISCAL_HALFYEAR, 
  FISCAL_YEAR, 
  SQL_TIMESTAMP, 
  CURRENT_ROW_IND, 
  EFFECTIVE_DATE, 
  EXPIRATION_DATE
FROM DIM_DATE
);

CREATE OR REPLACE SECURE VIEW VW_DIM_LOCATION AS
(
SELECT DIMLOCATIONID, ADDRESS, CITY, POSTALCODE, STATE_PROVINCE, COUNTRY
FROM DIM_LOCATION
)

CREATE OR REPLACE SECURE VIEW VW_DIM_PRODUCT AS
(
SELECT DimProductID, ProductID, ProductTypeID, 
  ProductCategoryID, ProductName, 
  ProductType, ProductCategory, ProductRetailPrice, 
  ProductWholesalePrice, ProductCost, 
  ProductRetailProfit, ProductWholesaleUnitProfit, 
  ProductProfitMarginUnitPercent
FROM DIM_PRODUCT
)

CREATE OR REPLACE SECURE VIEW VW_DIM_RESELLER AS
(
SELECT DIMRESELLERID, DIMLOCATIONID, RESELLERID, RESELLERNAME, CONTACTNAME, PHONENUMBER, EMAIL
FROM DIM_RESELLER
)

CREATE OR REPLACE SECURE VIEW VW_DIM_STORE AS
(
SELECT DIMSTOREID, DIMLOCATIONID, SOURCESTOREID, STORENUMBER, STOREMANAGER
FROM DIM_STORE
)

CREATE OR REPLACE SECURE VIEW VW_FACT_PRODUCTSALESTARGET AS
(
SELECT DIMPRODUCTID, DIMTARGETDATEID, PRODUCTTARGETSALESQUANTITY
FROM FACT_PRODUCTSALESTARGET
)

CREATE OR REPLACE SECURE VIEW VW_FACT_SALESACTUAL AS
(
SELECT DimProductID,
  DimStoreID, 
  DimResellerID, 
  DimCustomerID, 
  DimChannelID, 
  DimSaleDateID, 
  DimLocationID, 
  SourceSalesHeaderID, 
  SourceSalesDetailID, 
  SaleAmount, 
  SaleQuantity, 
  SaleUnitPrice, 
  SaleExtendedCost, 
  SaleTotalProfit
FROM FACT_SALESACTUAL
)

CREATE OR REPLACE SECURE VIEW VW_FACT_SRCSALESTARGET AS
(
SELECT DIMSTOREID, DIMRESELLERID, DIMCHANNELID, DIMTARGETDATEID, SALESTARGETAMOUNT
FROM FACT_SRCSALESTARGET
)

CREATE OR REPLACE SECURE VIEW VW_PRODUCT_SALES AS
(
SELECT DD.DAY_NAME, DS.STORENUMBER, DP.PRODUCTNAME, DP.PRODUCTTYPE, DP.PRODUCTCATEGORY, 
SUM(FS.SALEQUANTITY) AS QUANTITY, SUM(FS.SALEAMOUNT) AS SALE, SUM(FS.SALETOTALPROFIT) AS PROFIT
FROM FACT_SALESACTUAL FS
INNER JOIN DIM_DATE DD ON FS.DIMSALEDATEID = DD.DATE_PKEY
INNER JOIN DIM_STORE DS ON FS.DIMSTOREID = DS.DIMSTOREID
INNER JOIN DIM_PRODUCT DP ON FS.DIMPRODUCTID = DP.DIMPRODUCTID
WHERE STORENUMBER IN (5,8)
GROUP BY DD.DAY_NAME, DS.STORENUMBER, DP.PRODUCTNAME, DP.PRODUCTTYPE, DP.PRODUCTCATEGORY
ORDER BY DD.DAY_NAME, DS.STORENUMBER, DP.PRODUCTNAME
);


CREATE OR REPLACE SECURE VIEW VW_STATE_PERFORMANCE AS
(
SELECT DD.DATE, DD.DAY_NAME,DD.YEAR, DD.MONTH_NAME, DL.STATE_PROVINCE, X.STORE_COUNT,
DP.PRODUCTNAME, DP.PRODUCTTYPE, DP.PRODUCTCATEGORY,
SUM(FS.SALEQUANTITY) AS QUANTITY, SUM(FS.SALEAMOUNT) AS SALE, SUM(FS.SALETOTALPROFIT) AS PROFIT
FROM FACT_SALESACTUAL FS
INNER JOIN DIM_STORE DS ON FS.DIMSTOREID = DS.DIMSTOREID
INNER JOIN DIM_LOCATION DL ON DS.DIMLOCATIONID = DL.DIMLOCATIONID
INNER JOIN DIM_DATE DD ON FS.DIMSALEDATEID = DD.DATE_PKEY
INNER JOIN DIM_PRODUCT DP ON FS.DIMPRODUCTID = DP.DIMPRODUCTID
INNER JOIN 
(
SELECT DL.STATE_PROVINCE, COUNT(DS.STORENUMBER) STORE_COUNT
FROM DIM_STORE DS
INNER JOIN DIM_LOCATION DL ON DS.DIMLOCATIONID = DL.DIMLOCATIONID
WHERE DL.STATE_PROVINCE <> 'Unknown'  
GROUP BY DL.STATE_PROVINCE
) X ON DL.STATE_PROVINCE = X.STATE_PROVINCE
WHERE DL.STATE_PROVINCE <> 'Unknown'  
GROUP BY DD.DATE,  DD.DAY_NAME, DD.YEAR, DD.MONTH_NAME, DL.STATE_PROVINCE, X.STORE_COUNT,
DP.PRODUCTNAME, DP.PRODUCTTYPE, DP.PRODUCTCATEGORY
);