USE DATABASE IMT577_DW_KASHYAP_JAGWANI;

CREATE OR REPLACE SECURE VIEW VW_SALES_20132014 AS (
  SELECT *
  FROM DIM_PRODUCT dp
  INNER JOIN FACT_SALESACTUAL fsa ON dp.DimProductID = fsa.DimProductID
  INNER JOIN DIM_DATE dd ON fsa.DimSaleDateID = dd.Date_Pkey
  INNER JOIN DIM_STORE ds ON fsa.DimStoreID = ds.DimStoreID
  INNER JOIN FACT_SRCSALESTARGET fst ON ds.DimStoreID = fst.DimStoreID
  WHERE dd.Date BETWEEN '2013-01-01' AND '2014-12-31'
      AND ds.StoreNumber IN (5, 8)
  GROUP BY ds.StoreNumber, dp.ProductType
);

SELECT DISTINCT *
FROM DIM_PRODUCT dp
INNER JOIN FACT_SALESACTUAL fsa ON dp.DimProductID = fsa.DimProductID
INNER JOIN Dim_Date dd ON fsa.DimSaleDateID = dd.Date_Pkey
WHERE dd.Date BETWEEN '2013-01-01' AND '2013-12-31'
    AND dp.ProductType IN ('Women''s Casual', 'Men''s Casual')

//Q2
CREATE OR REPLACE SECURE VIEW VIEW_TOTAL_SALES_PROFIT
AS 
(
SELECT YEAR, 
       STORENUMBER,
       PROFIT, 
       SALE,
       SUM(SALE) OVER (PARTITION BY YEAR) AS TOTAL_SALES
      FROM
      (
      SELECT DD.Year, 
              DS.STORENUMBER,
              SUM(FS.SALEAMOUNT) AS SALE, 
              SUM(FS.SALETOTALPROFIT) AS PROFIT
      FROM FACT_SALESACTUAL FS
      INNER JOIN DIM_STORE DS ON FS.DIMSTOREID = DS.DIMSTOREID
      INNER JOIN DIM_PRODUCT DP ON FS.DIMPRODUCTID = DP.DIMPRODUCTID
      INNER JOIN DIM_DATE DD ON FS.DimSaleDateID = DD.DATE_PKEY
      WHERE DP.PRODUCTTYPE LIKE '%Casual' 
        AND STORENUMBER IN (5,8)
        AND LEFT(DIMSALEDATEID,4) IN (2013,2014)
      GROUP BY DD.Year, DS.STORENUMBER
      )
);

//Q3
CREATE OR REPLACE SECURE VIEW VW_STATE_PERFORMANCE AS
(
SELECT DD.DATE, DD.DAY_NAME,DD.YEAR, DD.MONTH_NAME, DL.STATE_PROVINCE, X.STORE_COUNT,
DP.PRODUCTNAME, DP.PRODUCTTYPE, DP.PRODUCTCATEGORY,
SUM(FS.SALEQUANTITY) AS QUANTITY, SUM(FS.SALEAMOUNT) AS SALE, SUM(FS.SALETOTALPROFIT) AS PROFIT
FROM FACT_SALESACTUAL FS
INNER JOIN DIM_STORE DS ON FS.DIMSTOREID = DS.DIMSTOREID
INNER JOIN DIM_LOCATION DL ON DS.DIMLOCATIONID = DL.DIMLOCATIONID
INNER JOIN DIM_DATE DD ON FS.DIMSALEDATEID = DD.DATE_PKEY
INNER JOIN DIM_PRODUCT DP ON FS.DIMPRODUCTID = DP.DIMPRODUCTID
INNER JOIN 
(
SELECT DL.STATE_PROVINCE, COUNT(DS.STORENUMBER) STORE_COUNT
FROM DIM_STORE DS
INNER JOIN DIM_LOCATION DL ON DS.DIMLOCATIONID = DL.DIMLOCATIONID
WHERE DL.STATE_PROVINCE <> 'Unknown'  
GROUP BY DL.STATE_PROVINCE
) X ON DL.STATE_PROVINCE = X.STATE_PROVINCE
WHERE DL.STATE_PROVINCE <> 'Unknown'  
GROUP BY DD.DATE,  DD.DAY_NAME, DD.YEAR, DD.MONTH_NAME, DL.STATE_PROVINCE, X.STORE_COUNT,
DP.PRODUCTNAME, DP.PRODUCTTYPE, DP.PRODUCTCATEGORY
);

//Q4
CREATE OR REPLACE SECURE VIEW VW_PRODUCT_SALES AS
(
SELECT DD.DAY_NAME, DS.STORENUMBER, DP.PRODUCTNAME, DP.PRODUCTTYPE, DP.PRODUCTCATEGORY, 
SUM(FS.SALEQUANTITY) AS QUANTITY, SUM(FS.SALEAMOUNT) AS SALE, SUM(FS.SALETOTALPROFIT) AS PROFIT
FROM FACT_SALESACTUAL FS
INNER JOIN DIM_DATE DD ON FS.DIMSALEDATEID = DD.DATE_PKEY
INNER JOIN DIM_STORE DS ON FS.DIMSTOREID = DS.DIMSTOREID
INNER JOIN DIM_PRODUCT DP ON FS.DIMPRODUCTID = DP.DIMPRODUCTID
WHERE STORENUMBER IN (5,8)
GROUP BY DD.DAY_NAME, DS.STORENUMBER, DP.PRODUCTNAME, DP.PRODUCTTYPE, DP.PRODUCTCATEGORY
ORDER BY DD.DAY_NAME, DS.STORENUMBER, DP.PRODUCTNAME
);

//Q1
CREATE OR REPLACE SECURE VIEW View_StorePerformanceAgainstTarget
AS SELECT A.STORENUMBER,A.DAY_NAME,A.MONTH_NUM_IN_YEAR,A.MONTH_NAME,A.YEAR,A.SALES_TARGET_AMOUNT,B.SALESAMOUNT
FROM (SELECT VDS.STORENUMBER,VDD.DAY_NAME,VDD.MONTH_NUM_IN_YEAR,VDD.MONTH_NAME,VDD.YEAR,ROUND(SUM(VFSSA.SALESTARGETAMOUNT),0) AS SALES_TARGET_AMOUNT
FROM VW_FACT_SRCSALESTARGET VFSSA
INNER JOIN VW_DIM_STORE VDS ON VDS.DIMSTOREID = VFSSA.DIMSTOREID
INNER JOIN VW_DIM_DATE VDD ON VDD.DATE_PKEY = VFSSA.DIMTARGETDATEID
GROUP BY 1,2,3,4,5
ORDER BY 2) AS A
INNER JOIN (SELECT VDS.STORENUMBER,VDD.DAY_NAME,VDD.MONTH_NUM_IN_YEAR,VDD.MONTH_NAME,VDD.YEAR,ROUND(SUM(VFSA.SALEAMOUNT),0) AS SALESAMOUNT
FROM VW_FACT_SALESACTUAL VFSA
INNER JOIN VW_DIM_STORE VDS ON VDS.DIMSTOREID = VFSA.DIMSTOREID
INNER JOIN VW_DIM_DATE VDD ON VDD.DATE_PKEY = VFSA.DIMSALEDATEID
GROUP BY 1,2,3,4,5
ORDER BY 2) AS B
ON A.STORENUMBER=B.STORENUMBER AND A.MONTH_NUM_IN_YEAR=B.MONTH_NUM_IN_YEAR AND A.MONTH_NAME=B.MONTH_NAME AND A.YEAR=B.YEAR and A.DAY_NAME = B.DAY_NAME
ORDER BY 1,2,4;
